/*---------------------------------------------------------------
 * Brand logos for keys, from Simple Icons (CC0; each mark stays its owner's).
 * Lucide leaves brands out. A key names one "brand:<Title>", so it never
 * meets a Lucide name; KeyIcon draws it filled, in the key's colour.
 *--------------------------------------------------------------*/

import {
    siAnthropic,
    siAmd,
    siAndroid,
    siApple,
    siApplemusic,
    siAudacity,
    siBattledotnet,
    siBlender,
    siBluesky,
    siBrave,
    siClaude,
    siCrunchyroll,
    siDavinciresolve,
    siDiscord,
    siDocker,
    siDropbox,
    siElgato,
    siEpicgames,
    siFacebook,
    siFigma,
    siFirefoxbrowser,
    siGit,
    siGithub,
    siGitlab,
    siGmail,
    siGoogle,
    siGooglechrome,
    siGoogledrive,
    siInstagram,
    siKick,
    siLinux,
    siMastodon,
    siMessenger,
    siNetflix,
    siNodedotjs,
    siNotion,
    siNvidia,
    siObsidian,
    siObsstudio,
    siOpera,
    siPatreon,
    siPaypal,
    siPlaystation,
    siPython,
    siReddit,
    siRiotgames,
    siSignal,
    siSnapchat,
    siSoundcloud,
    siSpotify,
    siSteam,
    siStreamlabs,
    siTelegram,
    siThreads,
    siTiktok,
    siTwitch,
    siUnity,
    siUnrealengine,
    siVlcmediaplayer,
    siWhatsapp,
    siWikipedia,
    siX,
    siYoutube,
    siZoom,
} from "simple-icons";

const LOGOS = [
    siDiscord,
    siObsstudio,
    siTwitch,
    siKick,
    siYoutube,
    siSpotify,
    siSoundcloud,
    siApplemusic,
    siSteam,
    siEpicgames,
    siBattledotnet,
    siRiotgames,
    siPlaystation,
    siGithub,
    siGitlab,
    siGit,
    siX,
    siBluesky,
    siThreads,
    siMastodon,
    siReddit,
    siInstagram,
    siFacebook,
    siTiktok,
    siTelegram,
    siWhatsapp,
    siSignal,
    siMessenger,
    siSnapchat,
    siZoom,
    siGoogle,
    siGmail,
    siGoogledrive,
    siGooglechrome,
    siFirefoxbrowser,
    siBrave,
    siOpera,
    siApple,
    siAndroid,
    siLinux,
    siNetflix,
    siCrunchyroll,
    siNotion,
    siObsidian,
    siFigma,
    siBlender,
    siUnity,
    siUnrealengine,
    siDavinciresolve,
    siAudacity,
    siVlcmediaplayer,
    siStreamlabs,
    siElgato,
    siNvidia,
    siAmd,
    siDocker,
    siNodedotjs,
    siPython,
    siDropbox,
    siPatreon,
    siPaypal,
    siWikipedia,
    siClaude,
    siAnthropic,
];

/** Each logo by its key icon name: its title, and its path on a 24 x 24 grid. */
export const BRAND_ICONS: Record<string, { title: string; path: string }> = Object.fromEntries(
    LOGOS.map((logo) => [`brand:${logo.title}`, { title: logo.title, path: logo.path }]),
);

/** The logos the icon picker offers before anything is searched. */
export const BRAND_DEFAULTS = [
    "brand:Discord",
    "brand:OBS Studio",
    "brand:Twitch",
    "brand:YouTube",
    "brand:Spotify",
    "brand:Steam",
    "brand:GitHub",
];
